project:
  type: book
  output-dir: docs

book:
  title: "rs"
  author: "Norah Jones"
  date: "2024/2/6"
  chapters:
    - week1.qmd
    - week.qmd
    - week3.qmd
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

