project:
  type: book
  output-dir: docs

book:
  title: "Remotely sensing - Learnig diary"
  author: "Siyu Yang"
  date: "2024/3/22"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week4.qmd
    - week5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

