# Week 1

## 1.1 summary

### 1.1.1 What is remote sensing?

Remote sensing is like a high-tech camera that takes pictures of the Earth. These "cameras" are installed on various platforms, such as high-altitude aircraft or drones and satellites. They capture details of the Earth's surface from long distances and help us understand and monitor changes in the environment.

### 1.1.2 Active and passive sensors

As mentioned above, these "cameras" are sensors. The difference between active and passive sensors mainly lies in the source of energy: passive sensors rely on energy reflected from the sun, while active sensors can actively emit electormagentic waves (such as radar waves or X-rays) and receive the signals reflected back. This significantly improves the performance and accuracy of active sensors at night or in adverse weather conditions.

### 1.1.3 Electromagnetic radiation

Remote sensing sensors primarily focus on receiving electromagnetic radiation, which includes all waves reflected from the surface of an object. In electromagnetic waves, the electric and magnetic fields are perpendicular to each other, and they are also perpendicular to the direction of propagation of the wave.
